### ISSUE TITLE
How to deal with multiple server versions running at the same time

### ISSUE THREAD

**Issue by bocasti** [zweidenker/SnapDump#25]
An idea that came up is to make server calls expect a version as first part of their path

This would help in the context of having multiple SnapDump servers running at the same time but with different versions.
A handler would have to use a version number in its url that matches the version of the target server.

I see the advantage as forcing snapdump users to consider version compatibility between handler and server.
We could have explicit error message when version numbers do not match. 
That could prevent server from perfoming inconsistent actions if versions are not compatible

Another solution would be to let snapdump users administrate such concern completly outside pharo.
If they use specific urls to target a a given instance of snapdump server, they should make sure the path that end up into snapdump server instance is "refined"

**Comment by noha** [comment]
Can you elaborate on the last paragraph? I‘m not sure I understand

**Comment by bocasti** [comment]
There is no concrete idea behind my last paragraph :) 
I just wanted to mention the possibility that: 
this issue (running multiple server at a time) could also be managed without modifying SnapDump code.

**Comment by bocasti** [comment]
Has been fixed with PR #26
