### ISSUE TITLE
"Invalid UT8 byte" while fetching stack trace of a reported snapshot

### ISSUE THREAD

**Issue by bocasti** [zweidenker/SnapDump#40]
From the UI client, if you click the "Stack trace" button, you get this kind of exception:

"Illegal leading byte for utf-8 encoding"

In order to reproduce, one could report a samp snaphot with this piece of code:

[Error signal: 'My first SnapDump snapshot']
    on: Error
    do: [ :error |
        Smalltalk  
        at: #SnapDump
        ifPresent: [ :reporter | 
	reporter handleException: error]].

The resulting snapshot snapshot will trigger the exception when fetch from a UI client

**Comment by noha** [comment]
has been solved with latest snap dump release
